### ISSUE TITLE
[Fix] Git Merge Conflict

### ISSUE THREAD

**Issue by KimJaeSeongJade** [loadingim/Slug_Idle#8]
# 발생일시
- 2024.10.25 _ 21:00경

# 내용
1. `Dev_ImJiYeon` -> `Develop` 브랜치 병합 시도 중 충돌 발생
2. Resolve Conflict가 불가능한 상황으로, 수동으로 수정해야 하는 상황 인지하였음.
3. 조치가 불가능한 상황으로 담당조교 개입하였음.

# 조치
![Fix_01](https://github.com/user-attachments/assets/b1e675b7-9bb2-45a6-a988-a2334b9bded0)
![Fix_02](https://github.com/user-attachments/assets/2aec4f30-9666-42c3-bb3a-8cd20fb07520)
![Fix_03](https://github.com/user-attachments/assets/df245158-8612-4e08-af33-37f301ad68ed)
![Fix_04](https://github.com/user-attachments/assets/d05055df-5fa9-404c-9b71-8a2b95142d32)

# 재발방지 방안
- 프로젝트 전제체에서 공유되는 설정 및 Ignore 등은 팀장 선에서 관리되도록 조치
- 자신이 생성하지 않은 파일의 삭제 및 변경 지양

# 조치 완료일시
- 2024.10.26 _ 15:00

**Comment by KimJaeSeongJade** [comment]
조치 완료된 사항이므로 Close 처리

**Comment by tjdeo1102** [comment]
넵 충분히 인지했습니다. 
추후,같은 이슈 발생하지 않도록, 프로젝트 전체 설정에 대한 부분 히스토리를 자세히 점검하여 Pull Request하겠습니다.
주말까지 고생해주신 조교님 감사합니다.

**Comment by VividSm** [comment]
이슈 내용 확인하였습니다.
해결해주셔서 감사합니다.!
